/*
 * NOTE: Autogenerated file using genllheaders.py
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * LL_DBGMCU_* macros live in stm32_ll_system.h across all SoCs;
 * provide this shim so soc_config.c's unconditional include resolves.
 */
#include <stm32_ll_system.h>
